CREATE TABLE IF NOT EXISTS user_transactions (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    quantity DOUBLE PRECISION NOT NULL,
    purchase_price DOUBLE PRECISION NOT NULL,
    transaction_type VARCHAR(10) NOT NULL DEFAULT 'buy',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
